name: Lock Threads
run-name: Lock stale threads

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: lock

permissions:
  contents: read

jobs:
  lock-threads:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: dessant/lock-threads@v5
        with:
          issue-inactive-days: 30
          pr-inactive-days: 30
          log-output: true
